package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CVAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCVAllPropertiesEquals(CV expected, CV actual) {
        assertCVAutoGeneratedPropertiesEquals(expected, actual);
        assertCVAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCVAllUpdatablePropertiesEquals(CV expected, CV actual) {
        assertCVUpdatableFieldsEquals(expected, actual);
        assertCVUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCVAutoGeneratedPropertiesEquals(CV expected, CV actual) {
        assertThat(actual)
            .as("Verify CV auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCVUpdatableFieldsEquals(CV expected, CV actual) {
        assertThat(actual)
            .as("Verify CV relevant properties")
            .satisfies(a -> assertThat(a.getUrlFichier()).as("check urlFichier").isEqualTo(expected.getUrlFichier()))
            .satisfies(a -> assertThat(a.getNomFichier()).as("check nomFichier").isEqualTo(expected.getNomFichier()))
            .satisfies(a -> assertThat(a.getDateUpload()).as("check dateUpload").isEqualTo(expected.getDateUpload()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCVUpdatableRelationshipsEquals(CV expected, CV actual) {
        // empty method
    }
}
