package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TypeContratAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeContratAllPropertiesEquals(TypeContrat expected, TypeContrat actual) {
        assertTypeContratAutoGeneratedPropertiesEquals(expected, actual);
        assertTypeContratAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeContratAllUpdatablePropertiesEquals(TypeContrat expected, TypeContrat actual) {
        assertTypeContratUpdatableFieldsEquals(expected, actual);
        assertTypeContratUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeContratAutoGeneratedPropertiesEquals(TypeContrat expected, TypeContrat actual) {
        assertThat(actual)
            .as("Verify TypeContrat auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeContratUpdatableFieldsEquals(TypeContrat expected, TypeContrat actual) {
        assertThat(actual)
            .as("Verify TypeContrat relevant properties")
            .satisfies(a -> assertThat(a.getNom()).as("check nom").isEqualTo(expected.getNom()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTypeContratUpdatableRelationshipsEquals(TypeContrat expected, TypeContrat actual) {
        // empty method
    }
}
